name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set AWS Region
      run: aws configure set region ap-south-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: private
        skip-logout: false

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 637423602870.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com
        ECR_REPOSITORY: hello-world
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Deploy to ECS
      env:
        CLUSTER_NAME: hello-world-cluster
        SERVICE_NAME: hello-world-service
        IMAGE_URI: ${{ steps.build-and-deploy.outputs.image }}
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
